services:
  nginx:
    image: docker.io/library/nginx:alpine-slim
    container_name: webserver
    hostname: nginx-webserver
    ports:
      - "80:80/tcp"
      - "443:443/udp"
      - "443:443/tcp"
    volumes:
      - ./logs:/var/log/nginx:rw
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:rw
    restart: unless-stopped

networks:
  podman:
    external: true
