services:
  nginx:
    image: docker.io/library/nginx:alpine-slim
    container_name: webserver
    hostname: nginx-webserver
    ports:
      - "443:443"
    volumes:
      - ./public:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:rw
    restart: unless-stopped

networks:
  podman:
    external: true

