apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: main
    image: docker.io/library/debian:stable-slim
    env:
    - name: KEY
      value: MYVALUE
    volumeMounts:
    - name: srv
      mountPath: /srv
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true

  - name: nginxrp
    image: localhost/nginxrp:latest
    ports:
    - containerPort: 443
      hostPort: 50030
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      readOnly: true
    - name: nginx-certs
      mountPath: /etc/nginx/certs

  volumes:
  - name: srv
    hostPath:
      path: ./srv
      type: DirectoryOrCreate
  - name: localtime
    hostPath:
      path: /etc/localtime
      type: File
  - name: nginx-conf
    hostPath:
      path: ./nginx/nginx.conf
      type: File
  - name: nginx-certs
    hostPath:
      path: ./nginx/certs
      type: DirectoryOrCreate

