apiVersion: v1
kind: Pod
metadata:
  name: nextcloud
spec:
  containers:
  - name: main
    image: lscr.io/linuxserver/nextcloud:latest
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    volumeMounts:
    - name: config
      mountPath: /config
    - name: data
      mountPath: /data
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true

  - name: nginx
    image: localhost/nginxrp:latest
    ports:
    - containerPort: 8443
      hostPort: 50010
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      readOnly: true
    - name: nginx-certs
      mountPath: /etc/nginx/certs
      readOnly: true

  volumes:
  - name: config
    hostPath:
      path: ./config
      type: DirectoryOrCreate
  - name: data
    hostPath:
      path: ./data
      type: DirectoryOrCreate
  - name: localtime
    hostPath:
      path: /etc/localtime
      type: File
  - name: nginx-conf
    hostPath:
      path: ./nginx.conf
      type: FileOrCreate
  - name: nginx-certs
    hostPath:
      path: ./certs
      type: Directory

