apiVersion: v1
kind: Pod
metadata:
  name: filebrowser
spec:
  containers:
  - name: main
    image: docker.io/filebrowser/filebrowser:s6
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    volumeMounts:
    - name: srv
      mountPath: /srv
    - name: database
      mountPath: /database
    - name: config
      mountPath: /config
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true

  - name: nginxrp
    image: localhost/nginxrp:latest
    ports:
    - containerPort: 443
      hostPort: 8443
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      readOnly: true
    - name: nginx-certs
      mountPath: /etc/nginx/certs

  volumes:
  - name: srv
    hostPath:
      path: ./srv
      type: DirectoryOrCreate
  - name: database
    hostPath:
      path: ./db
      type: DirectoryOrCreate
  - name: config
    hostPath:
      path: ./config
      type: DirectoryOrCreate
  - name: localtime
    hostPath:
      path: /etc/localtime
      type: File
  - name: nginx-conf
    hostPath:
      path: ./nginx/nginx.conf
      type: File
  - name: nginx-certs
    hostPath:
      path: ./nginx/certs
      type: DirectoryOrCreate

