services:
  nginx:
    build: .
    container_name: nginx
    hostname: nrproxy
    ports:
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:rw
    depends_on:
      - xapp
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge
    name: xnet

