apiVersion: v1
kind: Pod
metadata:
  name: jellyfin
spec:
  restartPolicy: Always
  hostNetwork: false

  containers:
  - name: main
    image: lscr.io/linuxserver/jellyfin:latest
    env:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true
    - name: config
      mountPath: /config
    - name: data
      mountPath: /data

  - name: nginx
    image: localhost/nginxrp:latest
    ports:
    - containerPort: 443
      hostPort: 8920
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true
    - name: nginx-conf
      mountPath: /etc/nginx/nginx.conf
      readOnly: true
    - name: nginx-certs
      mountPath: /etc/nginx/certs

  volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
      type: File
  - name: config
    hostPath:
      path: ./config
      type: DirectoryOrCreate
  - name: data
    hostPath:
      path: /path/to/media
      type: Directory
  - name: nginx-conf
    hostPath:
      path: ./nginx.conf
      type: File
  - name: nginx-certs
    hostPath:
      path: ./certs
      type: DirectoryOrCreate

