FROM docker.io/library/debian:stable-slim 
RUN apt-get update && apt-get install -y --no-install-recommends certbot python3 && rm -rf /var/lib/apt/lists/*
COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh
CMD [ "/entrypoint.sh" ]
