apiVersion: v1
kind: Pod
metadata:
  name: certbot
spec:
  restartPolicy: Always
  hostNetwork: false

  containers:
  - name: main
    image: certbot-temp:latest
    ports:
    - containerPort: 80
      hostPort: 80
    env:
    - name: DOMAIN
      value: example.com
    volumeMounts:
    - name: localtime
      mountPath: /etc/localtime
      readOnly: true
    - name: public
      mountPath: /public
    - name: letsencrypt
      mountPath: /etc/letsencrypt/

  volumes:
  - name: localtime
    hostPath:
      path: /etc/localtime
      type: File
  - name: public
    hostPath:
      path: ./public
      type: DirectoryOrCreate
  - name: letsencrypt
    hostPath:
      path: ./certs
      type: DirectoryOrCreate

